# Generated by Django 4.2.6 on 2024-01-02 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('berita', '0002_klinik'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jadwal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matkul1', models.CharField(max_length=100)),
                ('matkul2', models.CharField(max_length=100)),
                ('tanggal', models.CharField(max_length=100)),
            ],
        ),
    ]
