# Generated by Django 4.2.6 on 2024-01-02 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('berita', '0003_jadwal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('alamat', models.CharField(max_length=100)),
                ('usia', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Jadwal',
        ),
    ]
